#!/bin/sh

xrandr --output Virtual1 --mode 1440x900
picom &
~/bin/wlpset.sh &
xrdb -load ~/etc/x/xresources &
# ~/bin/bartime.sh | lemonbar -g 180x30+15+15 -b -f "Iosevka:normal:size=10" &
~/bin/bigbar.sh | lemonbar -g 270x30+15+15 -b -f "Iosevka:normal:size=10" &
# ~/bin/barcpu.sh | lemonbar -g 140x30+1285+15 -B '#101010' -b -f "SF Mono:normal:size=10" &
pgrep -x sxhkd || sxhkd -c ~/etc/sxhkd/sxhkdrc &
pgrep -x pulseaudio || pulseaudio --daemonize &
# st &
exec 2bwm
